language: ruby
rvm:
    - 2.2
env:
    - DB=mysql
before_script:
    - cp config/database.test.yml config/database.yml
    - cp .env.example .env
    - bundle install
script:
    - RAILS_ENV=test bin/rake db:create --trace
    - RAILS_ENV=test bin/rake db:migrate --trace
    - RAILS_ENV=test bin/rake spec --trace
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7e569f9f53d7c2c902a9 
  on_success: always  # options: [always|never|change] default: always
  on_failure: always  # options: [always|never|change] default: always
  on_start: false     # default: false
deploy:
  provider: opsworks
  access_key_id: AKIAISHOIMCAP2ZTDBIQ
  secret_access_key:
    secure: T66WKJYl/VSKd058mu8MYGy2cVhCbQRRnriVaGSN+ZmvxUwVBbVh321OIAT8TfMX4uAF8uTDZe9pPHUBQaxTwsas6VlevbPsH8NEtycTwbooeaNQ2EB3JP8kAIWEHF5XBI7MbiOG4uol0tkN4lA22A0v57GSJUoOPFk7P2I5RZ4=
  app-id: 6834df2a-4ac8-45fa-b3e2-268ee41e18fb
  migrate: true
  on:
    repo: usutani/lodge
    branch: travis
